### ISSUE TITLE
Can't edit ClusterRole: admiralty-multicluster-scheduler

### ISSUE THREAD

**Issue by lmxia** [admiraltyio/admiralty#100]
I encounter the error in proxy-scheduler, which said :
`E0322 09:41:30.568145       1 reflector.go:178] k8s.io/client-go@v0.18.9/tools/cache/reflector.go:125: Failed to list *v1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:serviceaccount:admiralty:admiralty-multicluster-scheduler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope`

So I edit the  ClusterRole, admiralty-multicluster-scheduler， to try to add the followling lines：
```
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - watch
  - list
  - get
```
But after I edited the clusterole successfully，the clusterrole become the origin content again.

I found the resourceVersion has been added one, so the clusterrole must be maintaind somewhere else.

 Any suggestions?
