### ISSUE TITLE
Install on GKE: insufficient quota to match these scopes

### ISSUE THREAD

**Issue by adrienjt** [admiraltyio/admiralty#124]
This issue is similar to https://github.com/open-policy-agent/gatekeeper/issues/1120

We added `priorityClassName: system-cluster-critical` to Admiralty pods in v0.14. GKE limits priority class consumption by default: https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default

- [ ] We need to include the following ResourceQuota in the Admiralty chart:

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: admiralty
  namespace: admiralty
spec:
  hard:
    pods: 12 # should cover the 4 deployments replica counts and rollout surges
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
```

- [ ] We need to run e2e tests on GKE in CI to catch errors like this sooner. (We'll soon have EKS and AKS tests in CI, so GKE should follow ASAP.)

Workaround in the meantime: add the ResourceQuota manually and retry.
