### ISSUE TITLE
Default priority is different in 2 clusters, preventing the federated pods from starting

### ISSUE THREAD

**Issue by dimm0** [admiraltyio/admiralty#152]
When submitting the pod:

```
➜  ~ k create -n ncmir-mm -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  annotations:
    multicluster.admiralty.io/elect: ""
  name: test-pod
spec:
  containers:
  - name: mypod
    image: centos:centos7
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
EOF
```

Getting the error:

`E0902 00:37:10.472210       1 controller.go:117] error syncing 'ncmir-mm/test-pod-j42mt': pods "test-pod-j42mt" is forbidden: the integer value of priority (0) must not be provided in pod spec; priority admission controller computed 1000 from the given PriorityClass name, requeuing`

in target cluster scheduler.

Target cluster:

```
➜  ~ k get priorityClass
NAME                                          VALUE        GLOBAL-DEFAULT   AGE
backfill                                      0            false            28d
default                                       1000         true             28d
openebs-lvm-localpv-csi-controller-critical   900000000    false            58d
openebs-lvm-localpv-csi-node-critical         900001000    false            58d
system-cluster-critical                       2000000000   false            76d
system-node-critical                          2000001000   false            76d
```

Source cluster:

```
➜  ~ k get priorityClass
NAME                        VALUE         GLOBAL-DEFAULT   AGE
kubevirt-cluster-critical   1000000000    false            590d
nice                        -10           false            3y192d
opportunistic               -2000000000   false            3y192d
opportunistic2              -1990000000   false            3y95d
owner                       10            false            3y185d
owner-no-preempt            10            false            548d
system-cluster-critical     2000000000    false            4y61d
system-node-critical        2000001000    false            4y61d
```
