### ISSUE TITLE
Diffrent ingress host or diffrent configmap

### ISSUE THREAD

**Issue by geekette86** [admiraltyio/admiralty#154]
Hey, i just came to know admiralty(great product) and my question is , can i sync different clusters but change the ingress host name or some config map

**Comment by geekette86** [comment]
Hello @adrienjt can i have a quick answer for this .thank you

**Comment by adrienjt** [comment]
Hi @geekette86, sorry for the delayed response. This isn't currently possible, but we've discussed cluster-specific pod transformations before: https://github.com/admiraltyio/admiralty/issues/96#issuecomment-749925709

The concept could be generalized to other types. You'd annotate your source ingress or configmap with `multicluster.admiralty.io/target-transformation: different-hostname`, referring to:

```
kind: TargetTransformation
metadata:
  name: different-hostname
transformations:
- targetSelector: 
    region: eu
  # maybe specify the GVK here, so we can type-check the patch when the TargetTransformation is created
  patch: |
    # user can define inline strategic merge patch here
```

Would that work for you? Would you like to implement and contribute this design?
