### ISSUE TITLE
CSIStorageCapacity no long supported from Kubernetes 1.27

### ISSUE THREAD

**Issue by nicksome168** [admiraltyio/admiralty#171]
## Scenario
- Ubuntu 22.04.2
- Admiralty 0.15

## Problem Description
After I created Kubernetes Jobs in the management cluster, the proxy pods are stuck in the everlasting Pending state. I checked the `admiralty-multicluster-scheduler-proxy-scheduler` deployment and seems like there are missing rbac rules.

The errors from the logs from `admiralty-multicluster-scheduler-proxy-scheduler` deployment 
```
W0627 17:30:23.203566       1 reflector.go:324] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
E0627 17:30:23.203580       1 reflector.go:138] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
```

I follow the exact installation steps from the [example](https://admiralty.io/docs/quick_start/) and stuck at this step:
```
for i in $(seq 1 10)
do
  cat <<EOF | kubectl --context kind-cd apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: global-$i
spec:
  template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item $i && sleep 5"]
        resources:
          requests:
            cpu: 100m
      restartPolicy: Never
EOF
done
```
