### ISSUE TITLE
Unable to Access Pod Logs in Source Cluster

### ISSUE THREAD

**Issue by takahashi-jo** [admiraltyio/admiralty#205]
## Scenario
- Admiralty 0.16.0
- Cert Manager 1.12.7
- AWS EKS 1.25

## Problem Description
I've successfully managed to deploy pods from a source cluster to a target cluster using the following Job configuration:  
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: admiralty-test
  namespace: xxxxxx
spec:
  template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item && sleep 5"]
        resources:
          requests:
            cpu: 10m
      restartPolicy: Never
```

Source Cluster:  
```sh
NAME                                             READY   STATUS      RESTARTS   AGE     IP              NODE                                             NOMINATED NODE   READINESS GATES
admiralty-test-m4w4b                             0/1     Completed   0          73s     10.254.16.169   admiralty-target-cluster-0f2eac64cb     <none>           <none>
```

Target Cluster:  
```sh
NAME                         READY   STATUS      RESTARTS   AGE   IP              NODE                                               NOMINATED NODE   READINESS GATES
admiralty-test-m4w4b-wcxbv   0/1     Completed   0          50s   10.254.16.169   ip-10-254-16-237.ap-northeast-1.compute.internal   <none>           <none>
```

While I can successfully access the pod logs in the target cluster, attempting to do so in the source cluster results in a connection refused error.  

Source Cluster:  
```sh
Processing item
```

Target Cluster:  
```sh
Error from server: Get "https://10.254.1.189:10250/containerLogs/xxxxxx/admiralty-test-m4w4b/c": dial tcp 10.254.1.189:10250: connect: connection refused
```

I'm able to access the logs in the target cluster without any issues, which suggests that the deployment and pod execution were successful. However, accessing the logs from the source cluster does not work as expected.  

Could this issue be related to a specific Admiralty configuration or perhaps a networking restriction within my Kubernetes setup? Any advice or guidance on troubleshooting this issue would be greatly appreciated.
