### ISSUE TITLE
Question - ability to specify the cluster and node for deployment

### ISSUE THREAD

**Issue by developeer** [admiraltyio/admiralty#99]
If I create a deployment and specify the cluster and a node? 
I have admiralty on cluster1 and want to deploy to cluster2 node 2.

apiVersion: v1
kind: Pod
metadata:
  name: nginx
template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
spec:
  containers:
  - name: nginx
    image: nginx
    nodeName: node2
    nodeSelector:
        topology.kubernetes.io/region: cluster2

**Comment by adrienjt** [comment]
For now, you'd have to use two nodeSelectors that are specific enough, one to select the virtual node representing the cluster (key1/value1), the other to select the node in that cluster (key2/value2):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    multicluster.admiralty.io/elect: ""
    multicluster.admiralty.io/proxy-pod-scheduling-constraints: |
      nodeSelector: # used in source cluster
        key1: value1
spec:
  nodeSelector: # used in target cluster
    key2: value2
```

You might actually already be able to specify the virtual node that represents the cluster with a nodeName:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    multicluster.admiralty.io/elect: ""
spec:
  nodeName: admiralty-cluster2 # used in source cluster (for now)
  nodeSelector: # used in target cluster
    key2: value2
```

But we should implement this instead:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    multicluster.admiralty.io/elect: ""
    multicluster.admiralty.io/proxy-pod-scheduling-constraints: |
      nodeName: admiralty-cluster2 # used in source cluster
spec:
  nodeName: node2 # used in target cluster
```
